name: Style

on:
  push:
    branches:
      # Push will only build on branches that match this name
      # Pull requests will override this, so pushes to pull requests will still build
      - master
  pull_request:
    branches:
      - master

jobs:
  check-style:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        poetry config virtualenvs.create false
        poetry install
    - name: Lint with ruff
      run: |
        pre-commit run --all-files
